services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - mp3_data:/tmp/kokito
      - ./backend/voces:/app/voces
      - portadas_data:/app/portadas
    environment:
      - DATABASE_URL=postgresql://kokito:kokito@db:5432/kokito
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./backend/.env
  worker:
    build: ./backend
    volumes:
      - ./backend:/app
      - mp3_data:/tmp/kokito
      - ./backend/voces:/app/voces
    environment:
      - DATABASE_URL=postgresql://kokito:kokito@db:5432/kokito
      - CELERY_BROKER_URL=redis://redis:6379/0
      - TTS_LOCAL_URL=http://192.168.1.51:8001
    depends_on:
      - db
      - redis
    command: celery -A celery_app worker --loglevel=info
    env_file:
      - ./backend/.env

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: kokito
      POSTGRES_PASSWORD: kokito
      POSTGRES_DB: kokito
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  mp3_data:
  portadas_data: