"""ruta_voz en libros

Revision ID: 04b945c930ea
Revises: e62cca4efc5c
Create Date: 2026-03-29 10:34:54.013525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b945c930ea'
down_revision: Union[str, Sequence[str], None] = 'e62cca4efc5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libros', sa.Column('ruta_voz', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libros', 'ruta_voz')
    # ### end Alembic commands ###
