"""metadatos libro

Revision ID: 40dfabad89ce
Revises: ca16bfed1dc1
Create Date: 2026-03-26 21:55:31.082588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40dfabad89ce'
down_revision: Union[str, Sequence[str], None] = 'ca16bfed1dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libros', sa.Column('sinopsis', sa.String(), nullable=True))
    op.add_column('libros', sa.Column('serie', sa.String(), nullable=True))
    op.add_column('libros', sa.Column('anio', sa.Integer(), nullable=True))
    op.add_column('libros', sa.Column('genero', sa.String(), nullable=True))
    op.add_column('libros', sa.Column('editorial', sa.String(), nullable=True))
    op.add_column('libros', sa.Column('isbn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libros', 'isbn')
    op.drop_column('libros', 'editorial')
    op.drop_column('libros', 'genero')
    op.drop_column('libros', 'anio')
    op.drop_column('libros', 'serie')
    op.drop_column('libros', 'sinopsis')
    # ### end Alembic commands ###
