"""aprobado en usuarios

Revision ID: 5befd5040621
Revises: 04b945c930ea
Create Date: 2026-03-29 18:00:20.060186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5befd5040621'
down_revision: Union[str, Sequence[str], None] = '04b945c930ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('aprobado', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'aprobado')
    # ### end Alembic commands ###
