"""titulo_parte y formato

Revision ID: 5e5b1533c900
Revises: 5befd5040621
Create Date: 2026-04-02 17:45:09.428686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5b1533c900'
down_revision: Union[str, Sequence[str], None] = '5befd5040621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libros', sa.Column('formato', sa.String(), server_default='pdf', nullable=False))
    op.add_column('partes', sa.Column('titulo_parte', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partes', 'titulo_parte')
    op.drop_column('libros', 'formato')
    # ### end Alembic commands ###
