"""novedades

Revision ID: a39985f32fd2
Revises: d73b329d31fd
Create Date: 2026-04-10 13:44:46.066993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39985f32fd2'
down_revision: Union[str, Sequence[str], None] = 'd73b329d31fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novedades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('contenido', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novedades_id'), 'novedades', ['id'], unique=False)
    op.create_table('novedades_vistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novedad_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_vista', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['novedad_id'], ['novedades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novedades_vistas_id'), 'novedades_vistas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_novedades_vistas_id'), table_name='novedades_vistas')
    op.drop_table('novedades_vistas')
    op.drop_index(op.f('ix_novedades_id'), table_name='novedades')
    op.drop_table('novedades')
    # ### end Alembic commands ###
