"""crear_tablas_iniciales

Revision ID: b7d77e2fe432
Revises: 
Create Date: 2026-03-23 18:55:13.839775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d77e2fe432'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('caracteres', sa.Integer(), nullable=True),
    sa.Column('proveedor', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversiones_id'), 'conversiones', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'usuario', name='rolusuario'), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('libros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('autor', sa.String(), nullable=True),
    sa.Column('hash_contenido', sa.String(), nullable=False),
    sa.Column('num_paginas', sa.Integer(), nullable=False),
    sa.Column('paginas_por_parte', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('subido_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_contenido')
    )
    op.create_index(op.f('ix_libros_id'), 'libros', ['id'], unique=False)
    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('titulo_solicitado', sa.String(), nullable=False),
    sa.Column('autor', sa.String(), nullable=True),
    sa.Column('notas', sa.String(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aceptada', 'rechazada', name='estadosolicitud'), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_id'), 'solicitudes', ['id'], unique=False)
    op.create_table('lista_deseos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('fecha_añadido', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lista_deseos_id'), 'lista_deseos', ['id'], unique=False)
    op.create_table('partes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('numero_parte', sa.Integer(), nullable=False),
    sa.Column('pagina_inicio', sa.Integer(), nullable=False),
    sa.Column('pagina_fin', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'procesando', 'listo', 'error', name='estadoparte'), nullable=True),
    sa.Column('ruta_mp3', sa.String(), nullable=True),
    sa.Column('proveedor', sa.String(), nullable=True),
    sa.Column('duracion_segundos', sa.Integer(), nullable=True),
    sa.Column('fecha_procesado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partes_id'), 'partes', ['id'], unique=False)
    op.create_table('estado_parte_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('parte_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'en_progreso', 'escuchada', name='estadopartusuario'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parte_id'], ['partes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estado_parte_usuario_id'), 'estado_parte_usuario', ['id'], unique=False)
    op.create_table('progreso_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('parte_id', sa.Integer(), nullable=False),
    sa.Column('segundo_actual', sa.Integer(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.ForeignKeyConstraint(['parte_id'], ['partes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progreso_usuario_id'), 'progreso_usuario', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progreso_usuario_id'), table_name='progreso_usuario')
    op.drop_table('progreso_usuario')
    op.drop_index(op.f('ix_estado_parte_usuario_id'), table_name='estado_parte_usuario')
    op.drop_table('estado_parte_usuario')
    op.drop_index(op.f('ix_partes_id'), table_name='partes')
    op.drop_table('partes')
    op.drop_index(op.f('ix_lista_deseos_id'), table_name='lista_deseos')
    op.drop_table('lista_deseos')
    op.drop_index(op.f('ix_solicitudes_id'), table_name='solicitudes')
    op.drop_table('solicitudes')
    op.drop_index(op.f('ix_libros_id'), table_name='libros')
    op.drop_table('libros')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_conversiones_id'), table_name='conversiones')
    op.drop_table('conversiones')
    # ### end Alembic commands ###
