"""portada_url en libros

Revision ID: c1874c0c9b82
Revises: b7d77e2fe432
Create Date: 2026-03-25 18:11:49.758960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1874c0c9b82'
down_revision: Union[str, Sequence[str], None] = 'b7d77e2fe432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libros', sa.Column('portada_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libros', 'portada_url')
    # ### end Alembic commands ###
