"""tarea_id en partes

Revision ID: ca16bfed1dc1
Revises: ffd5949ecec7
Create Date: 2026-03-26 20:41:13.857081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca16bfed1dc1'
down_revision: Union[str, Sequence[str], None] = 'ffd5949ecec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partes', sa.Column('tarea_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partes', 'tarea_id')
    # ### end Alembic commands ###
