"""orden_procesamiento en partes

Revision ID: d73b329d31fd
Revises: 5e5b1533c900
Create Date: 2026-04-09 16:41:05.428684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73b329d31fd'
down_revision: Union[str, Sequence[str], None] = '5e5b1533c900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partes', sa.Column('orden_procesamiento', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partes', 'orden_procesamiento')
    # ### end Alembic commands ###
