"""ruta_pdf en libros

Revision ID: e62cca4efc5c
Revises: 40dfabad89ce
Create Date: 2026-03-29 10:11:34.767170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e62cca4efc5c'
down_revision: Union[str, Sequence[str], None] = '40dfabad89ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libros', sa.Column('ruta_pdf', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libros', 'ruta_pdf')
    # ### end Alembic commands ###
