"""progreso por parte

Revision ID: ffd5949ecec7
Revises: c1874c0c9b82
Create Date: 2026-03-25 19:04:19.063531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd5949ecec7'
down_revision: Union[str, Sequence[str], None] = 'c1874c0c9b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progreso_parte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('parte_id', sa.Integer(), nullable=False),
    sa.Column('segundo_actual', sa.Integer(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parte_id'], ['partes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progreso_parte_id'), 'progreso_parte', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progreso_parte_id'), table_name='progreso_parte')
    op.drop_table('progreso_parte')
    # ### end Alembic commands ###
